# Generated by Django 4.2.11 on 2024-05-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='account_number',
        ),
    ]
